apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: 2023-4400-exp/4404-go-server-ci:bfbae1559acd62fc5297da3dcc77544fa1d01a28@sha256:cb7d8e17ffffb14d123b86a0d01107f16c1ba12859eb4289ff5c46031692d200
        name: go-server-ci
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-server-ci
  type: NodePort
